name: Feature Request
description: File new feature request
title: "[Feature Request]: "
labels: ["feature", "enhancement", "request"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request form !
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: curret-behavior
    attributes:
      label: What
      description: What is the current behavior ?
      placeholder: behavior
      value: | 
        The current behavior is doing ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: How
      description: what did you expect to happen ?
      placeholder: Tell us what you see!
      value: "I expected it to behave like this ..."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (latest)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
    id: non-extisting
    attributes:
      label: Request doesn't already exists
      description: By submitting this issue, you agree that you have checked this request is not related to an open issue or is already requested by other users
      options:
        - label: I agree this request is not a duplicate
          required: true
